# Multi-variable linear regression
## TensorFlow

In [1]:
import tensorflow as tf

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

In [3]:
# placeholders for a tensor that will be always fed
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name = 'weight1')
w2 = tf.Variable(tf.random_normal([1]), name = 'weight2')
w3 = tf.Variable(tf.random_normal([1]), name = 'weight3')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

In [8]:
# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# minimize. assign a very small  learning rate
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],\
                               feed_dict = {x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 100 == 0:
        print(step, 'Cost: ', cost_val, '\nPrediction:\n', hy_val)

0 Cost:  6204.3867 
Prediction:
 [231.89513 260.90475 266.42938 287.86945 196.47142]
100 Cost:  51.856983 
Prediction:
 [162.02919 177.46713 183.93793 198.07106 132.9358 ]
200 Cost:  49.131607 
Prediction:
 [161.75273 177.65656 183.85312 198.01051 133.18369]
300 Cost:  46.549885 
Prediction:
 [161.48366 177.84094 183.77055 197.95163 133.42494]
400 Cost:  44.10435 
Prediction:
 [161.22179 178.0204  183.69022 197.89435 133.65977]
500 Cost:  41.78788 
Prediction:
 [160.96687 178.19505 183.612   197.8386  133.88826]
600 Cost:  39.593666 
Prediction:
 [160.7188  178.36505 183.53587 197.78438 134.11064]
700 Cost:  37.515083 
Prediction:
 [160.47731 178.53049 183.46176 197.7316  134.32707]
800 Cost:  35.54616 
Prediction:
 [160.24228 178.69153 183.38965 197.68025 134.5377 ]
900 Cost:  33.681164 
Prediction:
 [160.01353 178.84827 183.31943 197.63031 134.74268]
1000 Cost:  31.91452 
Prediction:
 [159.79088 179.00081 183.25111 197.58171 134.94217]
1100 Cost:  30.24111 
Prediction:
 [159.57419 17

In [16]:
x_data = [[ 73.,  80.,  75.],
       [ 93.,  88.,  93.],
       [ 89.,  91.,  90.],
       [ 96.,  98., 100.],
       [ 73.,  66.,  70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

X = tf.placeholder(tf.float32, shape = [None, 3])
Y = tf.placeholder(tf.float32, shape = [None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],\
                               feed_dict = {X: x_data, Y: y_data})
    if step % 100 == 0:
        print(step, 'Cost: ', cost_val, '\nPrediction:\n', hy_val)

0 Cost:  5082.118 
Prediction:
 [[217.41205]
 [258.24326]
 [255.71935]
 [282.0083 ]
 [193.3462 ]]
100 Cost:  14.779654 
Prediction:
 [[154.1332 ]
 [182.41377]
 [180.88603]
 [200.51926]
 [135.5618 ]]
200 Cost:  14.232534 
Prediction:
 [[154.01682]
 [182.4946 ]
 [180.85168]
 [200.48409]
 [135.67657]]
300 Cost:  13.713287 
Prediction:
 [[153.9037 ]
 [182.5732 ]
 [180.81836]
 [200.44969]
 [135.78844]]
400 Cost:  13.220227 
Prediction:
 [[153.79367]
 [182.64964]
 [180.78596]
 [200.41597]
 [135.89745]]
500 Cost:  12.75216 
Prediction:
 [[153.68672]
 [182.724  ]
 [180.75453]
 [200.38297]
 [136.00368]]
600 Cost:  12.307786 
Prediction:
 [[153.58275]
 [182.79631]
 [180.72398]
 [200.35066]
 [136.1072 ]]
700 Cost:  11.885674 
Prediction:
 [[153.48169]
 [182.86665]
 [180.69434]
 [200.319  ]
 [136.20811]]
800 Cost:  11.484792 
Prediction:
 [[153.3834 ]
 [182.93504]
 [180.66551]
 [200.28798]
 [136.30646]]
900 Cost:  11.104049 
Prediction:
 [[153.28789]
 [183.00157]
 [180.63757]
 [200.25761]
 [136.40

## Loading Data from File

In [3]:
import numpy as np

In [26]:
xy = np.loadtxt('data-01-test-score.csv', delimiter = ',', dtype = np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data.shape, len(x_data))
print(y_data.shape)

(25, 3) 25
(25, 1)


In [25]:
tf.set_random_seed(777)

X = tf.placeholder(tf.float32, shape = [None, 3])
Y = tf.placeholder(tf.float32, shape = [None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],\
                               feed_dict = {X: x_data, Y: y_data})
    if step % 100 == 0:
        print(step, 'Cost: ', cost_val)
        #print('Prediction:\n', hy_val)
        
# predict the scores
print('Your score will be ', sess.run(hypothesis, feed_dict = {X: [[100, 70, 101]]}))
print('Their scores will be ', sess.run(hypothesis, feed_dict = {X: [[60, 70, 110], [90, 100, 80]]}))

0 Cost:  62817.01
100 Cost:  11.267891
200 Cost:  10.954045
300 Cost:  10.661304
400 Cost:  10.388141
500 Cost:  10.133163
600 Cost:  9.895073
700 Cost:  9.672641
800 Cost:  9.46479
900 Cost:  9.270478
1000 Cost:  9.088742
1100 Cost:  8.918727
1200 Cost:  8.75961
1300 Cost:  8.610632
1400 Cost:  8.471112
1500 Cost:  8.340385
1600 Cost:  8.21784
1700 Cost:  8.102958
1800 Cost:  7.9952016
1900 Cost:  7.894087
2000 Cost:  7.799204
Your score will be  [[188.35426]]
Their scores will be  [[171.88065]
 [177.35306]]


### Queue Runners

In [2]:
filename_queue = tf.train.string_input_producer(['data-01-test-score.csv'], \
                                                shuffle = False, name = 'filename_queue')
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# default values, in case of empty columns & specifies the type of the decoded result
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults = record_defaults)

# collect batches of csv in
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size = 10)

In [3]:
X = tf.placeholder(tf.float32, shape = [None, 3])
Y = tf.placeholder(tf.float32, shape = [None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [4]:
# start populating the filename queue
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess = sess, coord = coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], \
                                  feed_dict = {X: x_batch, Y: y_batch})
    if step % 20 == 0:
        print(step, 'Cost: ', cost_val, '\nPrediction:\n', hy_val)
        
coord.request_stop()
coord.join(threads)

0 Cost:  139692.4 
Prediction:
 [[-216.35493]
 [-247.6725 ]
 [-250.58159]
 [-273.25534]
 [-185.07765]
 [-134.66534]
 [-207.85475]
 [-159.29553]
 [-228.56926]
 [-210.78374]]
20 Cost:  48.285347 
Prediction:
 [[148.57103 ]
 [190.94006 ]
 [181.58614 ]
 [197.42827 ]
 [149.42055 ]
 [111.97832 ]
 [144.497   ]
 [101.956406]
 [181.3713  ]
 [168.96603 ]]
40 Cost:  47.891678 
Prediction:
 [[148.61513]
 [190.92809]
 [181.60738]
 [197.4571 ]
 [149.39055]
 [111.95745]
 [144.54535]
 [102.03159]
 [181.35204]
 [168.95506]]
60 Cost:  47.43516 
Prediction:
 [[148.64246 ]
 [190.89632 ]
 [181.6089  ]
 [197.46448 ]
 [149.34554 ]
 [111.925545]
 [144.5775  ]
 [102.0946  ]
 [181.31435 ]
 [168.927   ]]
80 Cost:  46.983482 
Prediction:
 [[148.66966 ]
 [190.86475 ]
 [181.61043 ]
 [197.47186 ]
 [149.30078 ]
 [111.893814]
 [144.60953 ]
 [102.1573  ]
 [181.27689 ]
 [168.89914 ]]
100 Cost:  46.53667 
Prediction:
 [[148.69669]
 [190.83333]
 [181.61195]
 [197.47917]
 [149.25626]
 [111.86229]
 [144.6414 ]
 [102.2197 ]


1020 Cost:  30.360638 
Prediction:
 [[149.78586 ]
 [189.55536 ]
 [181.66609 ]
 [197.78035 ]
 [147.43846 ]
 [110.593735]
 [145.95358 ]
 [104.78825 ]
 [179.74132 ]
 [167.78815 ]]
1040 Cost:  30.089197 
Prediction:
 [[149.8065  ]
 [189.53088 ]
 [181.66699 ]
 [197.7862  ]
 [147.40355 ]
 [110.569725]
 [145.97899 ]
 [104.838   ]
 [179.71295 ]
 [167.76823 ]]
1060 Cost:  29.820675 
Prediction:
 [[149.82704 ]
 [189.50656 ]
 [181.66788 ]
 [197.79199 ]
 [147.36882 ]
 [110.545876]
 [146.0043  ]
 [104.887505]
 [179.68478 ]
 [167.74846 ]]
1080 Cost:  29.555014 
Prediction:
 [[149.84746 ]
 [189.48238 ]
 [181.66878 ]
 [197.7978  ]
 [147.33427 ]
 [110.522156]
 [146.0295  ]
 [104.936775]
 [179.65678 ]
 [167.72882 ]]
1100 Cost:  29.292048 
Prediction:
 [[149.86775 ]
 [189.4583  ]
 [181.66963 ]
 [197.80353 ]
 [147.2999  ]
 [110.498566]
 [146.05455 ]
 [104.98581 ]
 [179.62892 ]
 [167.7093  ]]
1120 Cost:  29.031912 
Prediction:
 [[149.88794]
 [189.43437]
 [181.67049]
 [197.80927]
 [147.2657 ]
 [110.47511]
 

1980 Cost:  20.091806 
Prediction:
 [[150.65659]
 [188.51605]
 [181.69946]
 [198.03098]
 [145.95026]
 [109.58339]
 [147.04547]
 [106.92366]
 [178.54805]
 [166.97026]]
2000 Cost:  19.928453 
Prediction:
 [[150.67236]
 [188.49707]
 [181.69998]
 [198.03561]
 [145.923  ]
 [109.56513]
 [147.06563]
 [106.96307]
 [178.52649]
 [166.95587]]


## PyTorch

In [1]:
import torch
from torch.autograd import Variable
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

In [19]:
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super(LinearRegressionModel, self).__init__()
        self.linear = nn.Linear(3, 1, bias = True)
    def forward(self, x):
        return self.linear(x)

In [18]:
model = LinearRegressionModel()
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-5)

In [19]:
x_data = torch.tensor([[ 73.,  80.,  75.],
       [ 93.,  88.,  93.],
       [ 89.,  91.,  90.],
       [ 96.,  98., 100.],
       [ 73.,  66.,  70.]])
y_data = torch.tensor([[152.], [185.], [180.], [196.], [142.]])

for epoch in range(2001):
    inputs = Variable(x_data)
    target = Variable(y_data)
    out = model(inputs)
    loss = criterion(out, target)
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    if epoch in [0, 20, 40, 60, 80, 2000]:
        print(epoch, '\nCost: ', loss.data[0], '\nPrediction: \n', out)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number


0 
Cost:  tensor(13100.7168) 
Prediction: 
 tensor([[51.7628],
        [61.3103],
        [60.8637],
        [65.8595],
        [46.9899]], grad_fn=<ThAddmmBackward>)
20 
Cost:  tensor(1.9804) 
Prediction: 
 tensor([[153.3028],
        [183.3734],
        [181.1243],
        [196.8213],
        [140.0973]], grad_fn=<ThAddmmBackward>)
40 
Cost:  tensor(1.9611) 
Prediction: 
 tensor([[153.2934],
        [183.3816],
        [181.1223],
        [196.8200],
        [140.1076]], grad_fn=<ThAddmmBackward>)
60 
Cost:  tensor(1.9420) 
Prediction: 
 tensor([[153.2832],
        [183.3886],
        [181.1192],
        [196.8176],
        [140.1170]], grad_fn=<ThAddmmBackward>)
80 
Cost:  tensor(1.9231) 
Prediction: 
 tensor([[153.2730],
        [183.3956],
        [181.1161],
        [196.8152],
        [140.1264]], grad_fn=<ThAddmmBackward>)
2000 
Cost:  tensor(0.7990) 
Prediction: 
 tensor([[152.5138],
        [183.9178],
        [180.8857],
        [196.6312],
        [140.8264]], grad_fn=<ThAd

### Load from files - manually

In [30]:
xy = np.loadtxt('data-01-test-score.csv', delimiter = ',', dtype = np.float32)
x_data = torch.from_numpy(xy[:, 0:-1])
y_data = torch.from_numpy(xy[:, [-1]])

model = LinearRegressionModel()
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-5)

for epoch in range(100):
    # forward pass: compute predicted y by passing x to the model
    y_pred = model(x_data)
    loss = criterion(y_pred, y_data)
    if epoch % 10 == 0:
        print(epoch, loss.data[0])
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

0 tensor(38180.5000)
10 tensor(29.5627)
20 tensor(27.6072)
30 tensor(27.4736)
40 tensor(27.3410)
50 tensor(27.2093)
60 tensor(27.0785)
70 tensor(26.9485)
80 tensor(26.8195)
90 tensor(26.6913)


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  


### Load from files - with batch

In [ ]:
# training cycle  
for epoch in range(training_epochs):  
    # loop over all batches  
    for i in range(total_batch):  
        batch_xs, batch_ys = _, _

In the neural network terminology:
- one **epoch** = one forward pass and one backward pass of *all* the training exmaples
- **batch size** = # of training examples in the one forward/backward pass. The higher the batch size, the more memory space you'll need
- \# of **iterations** = # of passes, each pass using [batch size] # of examples. To be clear, one pass = one fw pass + one bw pass

Example: with 1000 training examples and with the batch size of 500, you need 2 iterations to finish 1 epoch

### with DataLoader

In [17]:
class ScoreDataset(Dataset):
    ''' Score dataset'''
    
    # initialize your data, download, etc.
    def __init__(self):
        # download, read data, etc.
        xy = np.loadtxt('data-01-test-score.csv', delimiter = ',', dtype = np.float32)
        self.len = xy.shape[0]
        self.x_data = torch.from_numpy(xy[:, 0:-1])
        self.y_data = torch.from_numpy(xy[:, [-1]])
        
    def __getitem__(self, index):
        # return one item on the index
        return self.x_data[index], self.y_data[index]
    
    def __len__(self):
        return self.len

In [24]:
dataset = ScoreDataset()
train_loader = DataLoader(dataset = dataset, batch_size = 10, shuffle = False)

In [25]:
model = LinearRegressionModel()
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-5)

In [26]:
for epoch in range(3):
    for i, data in enumerate(train_loader, 0): # train_loader -> iterable
        # get the inputs
        inputs, labels = data
    
        # wrap them in Variable
        inputs, labels = Variable(inputs), Variable(labels)
    
        # run your training process
        #print(epoch, i, 'inputs', inputs.data, 'labels', labels.data)
    
        y_pred = model(inputs)
        loss = criterion(y_pred, labels)
    
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        print(epoch, i, '\nCost: ', loss.data[0], '\nPrediction: \n', y_pred)

0 0 
Cost:  tensor(33259.2578) 
Prediction: 
 tensor([[-17.8671],
        [-28.8485],
        [-24.5735],
        [-27.6166],
        [-23.0884],
        [-19.1195],
        [-19.8090],
        [-13.2798],
        [-29.6720],
        [-29.9746]], grad_fn=<ThAddmmBackward>)
0 1 
Cost:  tensor(13573.4697) 
Prediction: 
 tensor([[40.0831],
        [36.0037],
        [54.8527],
        [46.3095],
        [41.9919],
        [49.9399],
        [42.8509],
        [52.6997],
        [53.5528],
        [48.5756]], grad_fn=<ThAddmmBackward>)
0 2 
Cost:  tensor(5929.4912) 
Prediction: 
 tensor([[ 98.3548],
        [ 94.4966],
        [ 94.6363],
        [ 92.6496],
        [106.2801]], grad_fn=<ThAddmmBackward>)
1 0 
Cost:  tensor(1652.2717) 
Prediction: 
 tensor([[120.0126],
        [136.9013],
        [138.7258],
        [150.2372],
        [103.3234],
        [ 74.0956],
        [113.3247],
        [ 85.4221],
        [125.2505],
        [113.5429]], grad_fn=<ThAddmmBackward>)
1 1 
Cost:  tens

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
